version: '3.1'

services:

  mariadb-transcribeapi:
    image: mariadb:latest
    container_name: mariadb-transcribeapi
    environment:
      - MYSQL_DATABASE=transcribe
      - MYSQL_USER=transcribe
      - MYSQL_PASSWORD=transcribe
      - MYSQL_ROOT_PASSWORD=transcribe
    networks:
      - mariadb-transcribeapi-network
    volumes:
      - mariadb_transcribe_data:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

  transcribeapi:
    container_name: transcribeapi
    image: transcribeapi:latest
    ports:
      - "8088:8088"
    depends_on:
      - mariadb-transcribeapi
    volumes:
    - ./data:/data
    environment:
      - DATABASE_HOST=mariadb-transcribeapi
      - DATABASE_DB=transcribe
      - DATABASE_USER=transcribe
      - DATABASE_PASSWORD=transcribe
      - DATABASE_PORT=3306
volumes:
  mariadb_transcribe_data:
